catalog:
  '@antfu/eslint-config': ^5.2.1
  '@eslint/js': ^9.32.0
  eslint: ^9.33.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-vue: ^10.4.0
  globals: ^16.3.0
  husky: ^9.1.7
  jiti: ^2.5.1
  lint-staged: ^16.1.5
  lodash-es: ^4.17.21
  prettier: ^3.6.2
  tsdown: ^0.14.1
  typescript: ^5.9.2
  typescript-eslint: ^8.39.0
catalogs:
  conflicts_eslint_h9_32_0:
    eslint: ^9.32.0
  conflicts_tsdown_h0_14_0:
    tsdown: ^0.14.0
