catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
catalog:
  '@antfu/eslint-config': ^7.4.3
  '@eslint/config-inspector': ^1.4.2
  eslint: ^10.0.0
  eslint-plugin-format: ^1.4.0
  husky: ^9.1.7
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  prettier: ^3.8.1
  prettier-plugin-lint-md: ^1.0.1
  tsdown: ^0.20.3
  typescript: ^5.9.3
