catalog:
  '@antfu/eslint-config': ^6.2.0
  '@eslint/config-inspector': ^1.3.0
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  husky: ^9.1.7
  jiti: ^2.6.1
  lint-staged: ^16.2.6
  prettier: ^3.6.2
  prettier-plugin-lint-md: ^1.0.1
  tsdown: ^0.16.1
  typescript: ^5.9.3

catalogMode: strict
