catalog:
  '@antfu/eslint-config': ^5.2.1
  '@eslint/config-inspector': ^1.2.0
  eslint: ^9.34.0
  eslint-plugin-format: ^1.0.1
  husky: ^9.1.7
  lint-staged: ^16.1.5
  prettier: ^3.6.2
  tsdown: ^0.14.2
  typescript: ^5.9.2

catalogMode: strict
