name: Release Workflow
on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - id: npm_publish
        name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
