name: Release Workflow
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup_pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - id: install_dependencies
        name: Install dependencies
        run: pnpm install
      - id: publish
        name: Publish
        run: pnpm publish --no-git-checks
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
